[webservers]
web-1 ansible_host=158.160.112.237 fqdn=fhms3ar07g0gb421akse.auto.internal
web-2 ansible_host=158.160.116.50 fqdn=fhmbkbtpufli6ppo5v29.auto.internal

[databases]
main ansible_host=130.193.39.51 fqdn=fhmkkls7sbk6ilbhrfsc.auto.internal
replica ansible_host=89.169.128.25 fqdn=fhmuusd3hj708ao7dfrg.auto.internal

[storage]
storage ansible_host=158.160.109.19 fqdn=fhm1bo2olo6r13u1i3gq.auto.internal
