[webservers]
web-1 ansible_host=84.201.158.155 fqdn=fhmnu6v9eppotsjfjat7.auto.internal
web-2 ansible_host=158.160.47.75 fqdn=fhmd7ss5l4c693r48j1u.auto.internal

[databases]
main ansible_host=158.160.112.232 fqdn=fhm1f4p4tcudhqmjphr0.auto.internal
replica ansible_host=89.169.151.152 fqdn=fhmvl6ol8t97a84ts1b0.auto.internal

[storage]
storage ansible_host=89.169.152.140 fqdn=fhmjlrpro9ll56rmfqrh.auto.internal
